export {
  always,
  createInertia,
  lazy,
  optional,
  type InertiaAdapter,
  type InertiaOptions,
  type InertiaPage,
  type InertiaProp,
  type InertiaPropKind,
  type InertiaPropResolver,
  type InertiaProps,
  type InertiaRootView,
  type InertiaRootViewProps,
} from "./inertia";
